// flow-typed signature: e13efbfa6b188661dabd2a848b9e0c45
// flow-typed version: <<STUB>>/@eric.dahlseng/configuration-build_v^0.1.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@eric.dahlseng/configuration-build'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@eric.dahlseng/configuration-build' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@eric.dahlseng/configuration-build/dist/cli' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/configuration-build/dist/index' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/configuration-build/dist/utils' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/configuration-build/dist/webpack.template' {
  declare module.exports: any;
}

// Filename aliases
declare module '@eric.dahlseng/configuration-build/dist/cli.js' {
  declare module.exports: $Exports<'@eric.dahlseng/configuration-build/dist/cli'>;
}
declare module '@eric.dahlseng/configuration-build/dist/index.js' {
  declare module.exports: $Exports<'@eric.dahlseng/configuration-build/dist/index'>;
}
declare module '@eric.dahlseng/configuration-build/dist/utils.js' {
  declare module.exports: $Exports<'@eric.dahlseng/configuration-build/dist/utils'>;
}
declare module '@eric.dahlseng/configuration-build/dist/webpack.template.js' {
  declare module.exports: $Exports<'@eric.dahlseng/configuration-build/dist/webpack.template'>;
}
