// flow-typed signature: c9469edd206db0a9b9d52a4652521f7b
// flow-typed version: <<STUB>>/@eric.dahlseng/linter-configuration_v^0.3.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@eric.dahlseng/linter-configuration'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@eric.dahlseng/linter-configuration' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@eric.dahlseng/linter-configuration/dist/commit' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/linter-configuration/dist/css' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/linter-configuration/dist/index' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/linter-configuration/dist/javascript' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/linter-configuration/dist/json' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/linter-configuration/dist/prettier' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/linter-configuration/dist/terraform' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/linter-configuration/dist/utils' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/linter-configuration/dist/yaml' {
  declare module.exports: any;
}

// Filename aliases
declare module '@eric.dahlseng/linter-configuration/dist/commit.js' {
  declare module.exports: $Exports<'@eric.dahlseng/linter-configuration/dist/commit'>;
}
declare module '@eric.dahlseng/linter-configuration/dist/css.js' {
  declare module.exports: $Exports<'@eric.dahlseng/linter-configuration/dist/css'>;
}
declare module '@eric.dahlseng/linter-configuration/dist/index.js' {
  declare module.exports: $Exports<'@eric.dahlseng/linter-configuration/dist/index'>;
}
declare module '@eric.dahlseng/linter-configuration/dist/javascript.js' {
  declare module.exports: $Exports<'@eric.dahlseng/linter-configuration/dist/javascript'>;
}
declare module '@eric.dahlseng/linter-configuration/dist/json.js' {
  declare module.exports: $Exports<'@eric.dahlseng/linter-configuration/dist/json'>;
}
declare module '@eric.dahlseng/linter-configuration/dist/prettier.js' {
  declare module.exports: $Exports<'@eric.dahlseng/linter-configuration/dist/prettier'>;
}
declare module '@eric.dahlseng/linter-configuration/dist/terraform.js' {
  declare module.exports: $Exports<'@eric.dahlseng/linter-configuration/dist/terraform'>;
}
declare module '@eric.dahlseng/linter-configuration/dist/utils.js' {
  declare module.exports: $Exports<'@eric.dahlseng/linter-configuration/dist/utils'>;
}
declare module '@eric.dahlseng/linter-configuration/dist/yaml.js' {
  declare module.exports: $Exports<'@eric.dahlseng/linter-configuration/dist/yaml'>;
}
