// flow-typed signature: 2f27002ee3502e8a0cc36d0c94383fa4
// flow-typed version: <<STUB>>/@eric.dahlseng/standard-version_v^1.0.3/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@eric.dahlseng/standard-version'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@eric.dahlseng/standard-version' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@eric.dahlseng/standard-version/bin/cli' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/standard-version/command' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/standard-version/lib/checkpoint' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/standard-version/lib/format-commit-message' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/standard-version/lib/latest-semver-tag' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/standard-version/lib/lifecycles/bump' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/standard-version/lib/lifecycles/changelog' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/standard-version/lib/lifecycles/commit' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/standard-version/lib/lifecycles/tag' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/standard-version/lib/print-error' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/standard-version/lib/run-exec' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/standard-version/lib/run-lifecycle-hook' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/standard-version/lib/run-lifecycle-script' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/standard-version/lib/write-file' {
  declare module.exports: any;
}

declare module '@eric.dahlseng/standard-version/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@eric.dahlseng/standard-version/bin/cli.js' {
  declare module.exports: $Exports<'@eric.dahlseng/standard-version/bin/cli'>;
}
declare module '@eric.dahlseng/standard-version/command.js' {
  declare module.exports: $Exports<'@eric.dahlseng/standard-version/command'>;
}
declare module '@eric.dahlseng/standard-version/index' {
  declare module.exports: $Exports<'@eric.dahlseng/standard-version'>;
}
declare module '@eric.dahlseng/standard-version/index.js' {
  declare module.exports: $Exports<'@eric.dahlseng/standard-version'>;
}
declare module '@eric.dahlseng/standard-version/lib/checkpoint.js' {
  declare module.exports: $Exports<'@eric.dahlseng/standard-version/lib/checkpoint'>;
}
declare module '@eric.dahlseng/standard-version/lib/format-commit-message.js' {
  declare module.exports: $Exports<'@eric.dahlseng/standard-version/lib/format-commit-message'>;
}
declare module '@eric.dahlseng/standard-version/lib/latest-semver-tag.js' {
  declare module.exports: $Exports<'@eric.dahlseng/standard-version/lib/latest-semver-tag'>;
}
declare module '@eric.dahlseng/standard-version/lib/lifecycles/bump.js' {
  declare module.exports: $Exports<'@eric.dahlseng/standard-version/lib/lifecycles/bump'>;
}
declare module '@eric.dahlseng/standard-version/lib/lifecycles/changelog.js' {
  declare module.exports: $Exports<'@eric.dahlseng/standard-version/lib/lifecycles/changelog'>;
}
declare module '@eric.dahlseng/standard-version/lib/lifecycles/commit.js' {
  declare module.exports: $Exports<'@eric.dahlseng/standard-version/lib/lifecycles/commit'>;
}
declare module '@eric.dahlseng/standard-version/lib/lifecycles/tag.js' {
  declare module.exports: $Exports<'@eric.dahlseng/standard-version/lib/lifecycles/tag'>;
}
declare module '@eric.dahlseng/standard-version/lib/print-error.js' {
  declare module.exports: $Exports<'@eric.dahlseng/standard-version/lib/print-error'>;
}
declare module '@eric.dahlseng/standard-version/lib/run-exec.js' {
  declare module.exports: $Exports<'@eric.dahlseng/standard-version/lib/run-exec'>;
}
declare module '@eric.dahlseng/standard-version/lib/run-lifecycle-hook.js' {
  declare module.exports: $Exports<'@eric.dahlseng/standard-version/lib/run-lifecycle-hook'>;
}
declare module '@eric.dahlseng/standard-version/lib/run-lifecycle-script.js' {
  declare module.exports: $Exports<'@eric.dahlseng/standard-version/lib/run-lifecycle-script'>;
}
declare module '@eric.dahlseng/standard-version/lib/write-file.js' {
  declare module.exports: $Exports<'@eric.dahlseng/standard-version/lib/write-file'>;
}
declare module '@eric.dahlseng/standard-version/test.js' {
  declare module.exports: $Exports<'@eric.dahlseng/standard-version/test'>;
}
